name: Events Demo
on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - dev-*
      - feat/**
    paths-ignore:
      - ".github/**"
  push:
    branches:
      - main
      - dev-*
      - feat/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Console Event Details
        run: echo "${{toJson(github.event)}}"
