name: Execution Flow Check
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    environment: testing
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    strategy:
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependency
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test Application
        continue-on-error: true
        run: npm test -- --json --outputFile=output.json
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: output.json

  build:
    needs: [test]
    runs-on: ubuntu-latest
    environment: testing
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
    steps:
      - name: Get the Code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache Dependency
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Application
        run: npm run build
